src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use PhpParser\Node\Stmt\Return_;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $nbPlaceTotal = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateFin = null;

    #[ORM\Column(length: 100)]
    private ?string $intitule = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Formation $formation = null;

    #[ORM\ManyToMany(targetEntity: Stagiaire::class, inversedBy: 'sessions', cascade: ['persist'])]
    private Collection $stagiaires;

    #[ORM\OneToMany(mappedBy: 'session', targetEntity: Programme::class, cascade: ['persist', 'remove'], orphanRemoval:true )]
    private Collection $programmes;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $user = null;

    public function __construct()
    {
        $this->stagiaires = new ArrayCollection();
        $this->programmes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbPlaceTotal(): ?int
    {
        return $this->nbPlaceTotal;
    }

    public function setNbPlaceTotal(int $nbPlaceTotal): static
    {
        $this->nbPlaceTotal = $nbPlaceTotal;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): static
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): static
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): static
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): static
    {
        $this->formation = $formation;

        return $this;
    }

    /**
     * @return Collection<int, Stagiaire>
     */
    public function getStagiaires(): Collection
    {
        return $this->stagiaires;
    }

    public function addStagiaire(Stagiaire $stagiaire): static
    {
        if (!$this->stagiaires->contains($stagiaire)) {
            $this->stagiaires->add($stagiaire);
        }

        return $this;
    }

    public function removeStagiaire(Stagiaire $stagiaire): static
    {
        $this->stagiaires->removeElement($stagiaire);

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): static
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes->add($programme);
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): static
    {
        if ($this->programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->intitule;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

   
    public function getEtat()
    {
        $now = new \DateTime('now');
        if($this->dateDebut > $now) {
            return ' a venir';
        }elseif($this->dateFin < $now){
            return 'Terminé';
        }else{
            return 'En cour';
        }
       
        return;
    }

}

src/Entity/Stagiaire.php
<?php

namespace App\Entity;

use App\Repository\StagiaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StagiaireRepository::class)]
class Stagiaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200)]
    private ?string $nom = null;

    #[ORM\Column(length: 200)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateNaissance = null;

    #[ORM\Column(length: 8)]
    private ?string $genre = null;

    #[ORM\Column(length: 180)]
    private ?string $ville = null;

    #[ORM\Column(length: 50)]
    private ?string $email = null;

    #[ORM\Column(length: 15)]
    private ?string $tel = null;

    #[ORM\ManyToMany(targetEntity: Session::class, mappedBy: 'stagiaires', cascade: ['persist'])]
    private Collection $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): static
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): static
    {
        $this->tel = $tel;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): static
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
            $session->addStagiaire($this);
        }

        return $this;
    }

    public function removeSession(Session $session): static
    {
        if ($this->sessions->removeElement($session)) {
            $session->removeStagiaire($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }

    public function getAge()
    {
        $now = new \DateTime();
        $interval = $this->dateNaissance->diff($now);
        return $interval->format("%Y");
    }

}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Entity\Formation;
use App\Entity\Programme;
use App\Form\SessionType;
use App\Form\AddStagiaire;
use App\Form\FormationType;
use App\Form\ProgrammeType;
use App\Form\ModuleSessionType;
use App\Form\AddModulesSessionType;
use App\Repository\FormationRepository;
use App\Repository\SessionRepository;
use App\Repository\StagiaireRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SessionController extends AbstractController
{
    //Function pour afficher la liste des sessions********************************************************
    //Chemin d'accès de la pages https://127.0.0.1:8000/session
    #[Route('session', name: 'app_session')]
    public function index(SessionRepository $sessionRepository): Response
    {
        $sessions = $sessionRepository->findBy([],["DateDebut" => "ASC"]);//récupère les toutes les données de la table session
        //return le résultat sur le template  session/index
        return $this->render('session/index.html.twig', [
            'sessions' => $sessions,
        ]);
    }

   
//*Pour afficher le programme d'une session******************************************************************** */
//chemin d'acès a la page  https://127.0.0.1:8000/session/detail1  
    #[Route('/session/detail{id}', name: 'app_detailSession')]
    //on utilise Session pour récupérer son id
    public function detailSession(Session $session): Response
    {
    
        //renvoie le resultat de la session sélectionné par son id vers le template detailSession
        return $this->render('session/detailSession.html.twig', [
            'session' => $session,
        ]);
    }    


    //Pour afficher la liste des session trier par formation(dev, bureautique,.....)
    #[Route('/session/listeSession{id}', name: 'app_listeSessionParFormation')]
    public function listeSessionParFormation(Formation $formation, EntityManagerInterface $entityManager): Response
    {
        $sessions = $entityManager->getRepository(Session::class)->findBy(
            ['formation' => $formation],
            ['dateDebut' => 'ASC'] // Tri par date de début en ordre croissant
        );
        
        //renvoie le liste des session contenu dans une formation par son identifiant 
        return $this->render('session/listeSessionParFormation.html.twig', [
            'formation' => $formation,
            'sessions' => $sessions,
            
        ]);
    }    

   

    //Function pour ajouter et editer une nouvelle formation*******************************************************
    #[Route('formation/new', name: 'new_formation')]
    #[Route('formation/{id}/edit', name: 'edit_formation')]
    public function newFormation(Formation $formation = null, Request $request, EntityManagerInterface $entityManager): Response
    {
        //si formation n'existe pas on créer une nouvelle instance pour l'ajout
        if(!$formation){
            $formation = new Formation();
            $this->addFlash(
                'notice',
                'Session ajouté avec succès!'
            );
        }

        //creer le formulaire
        $form = $this->createForm(FormationType::class, $formation);
        //recupère les données du formulaire si il a été soumis et validé
        $form->handleRequest($request);
        //si le formulaire est remplie et valide
        if ($form->isSubmitted() && $form->isValid()) {
            //récupère les donné du formulaire  
            $formation = $form->getData();
            // prepare PDO(prepare la requete Insert ou Update)
            $entityManager->persist($formation);
            // execute PDO(la requete Insert ou Update)
            $entityManager->flush();
            //redirige ver le home qui est la liste des formation
            return $this->redirectToRoute('app_home');
        }
        //return la vue du formullaire en cas d'erreur
        return $this->render('session/new_formation.html.twig', [
            'form' => $form,//pour la creation du formulaire 
            'edit' => $formation->getId(),//renvoie edit vers le template du formulaire pour pouvoir définir si edit ou add
            'formation' => $formation,
        ]);
    }
   

    #[Route('formation/{id}/delete', name: 'delete_formation')]
    public function deleteFormation(Formation $formation, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($formation);
        $entityManager->flush();

        $this->addFlash(
            'notice',
            'Formation supprimé!'
        );

        return $this->redirectToRoute('app_home');
    }

    

/******Ajout et Modification d'une session*********************************************** */
    #[Route('session/{idFormation}/new', name: 'new_session')]
    #[Route('session/{id}/edit', name: 'edit_session')]
    public function newSession(Session $session = null, Request $request, EntityManagerInterface $entityManager, FormationRepository $formationRepository, StagiaireRepository $stagiaireRepository): Response
    {   
        
        if(!$session){
            //si session n'existe pas creer une nouvelle instance
            $session = new Session();  
            $idFormation = $request->attributes->get('idFormation'); //on recupère l'id de la formation contenu dans l'url
            $formation = $formationRepository->findOneBy(['id'=> $idFormation]);//on récupère la formation grace a cet id
        }else{
            
            $formation = $session->getFormation();// si la session existe déja on recupère sa formation

        }
       
        $session->setFormation($formation); // on inclu la session existante ou la nouvelle dans sa formation
        
       

        $form = $this->createForm(SessionType::class, $session);//creer le formulaire
        //recupère les données du formulaire si il a été soumis et validé
        $form->handleRequest($request);
        
        //si le formulaire est soumit et valide 
        $nbPlaceRestante = $session->getnbPlaceTotal() - count($session->getStagiaires());
        // dd($nbPlaceRestante);
        // die;
        if ($form->isSubmitted() && $form->isValid() && $nbPlaceRestante >= 0 ) {
            //récupère les donné du formulaire 
            $sessions = $form->getData();
            

            // prepare PDO la requete insert ou update
            $entityManager->persist($session);
            // execute PDO la requete insert ou update
            $entityManager->flush();
            
           return $this->redirectToRoute('app_detailSession', ['id'=> $session->getId()]);
    
        }
        // sinon return sur le formulaire pour corriger les ereur
        return $this->render('session/new_session.html.twig', [
            'form' => $form->createView(),
            'edit' => $session->getId(),
            'sessionId' => $session->getId(),
            'session' => $session,
            'formation' => $formation,
        ]);
    }  


    #[Route('session/{id}/delete_session', name: 'delete_session')]
    public function deleteSession(Session $session, EntityManagerInterface $entityManager): Response
    {   
        
        $entityManager->remove($session);
        $entityManager->flush();


        return $this->redirectToRoute('app_home');
      
          
    }  

    #[Route('session/{id}/unset_module', name: 'app_unsetModule')]
    public function unsetModule(Programme $programme, EntityManagerInterface $entityManager): Response
    {   
       $module = $programme->getModule();
       $session = $programme->getSession();
        $session->removeProgramme($programme);
        $module->removeProgramme($programme);
        $entityManager->persist($programme);
        // execute PDO la requete insert ou update
        $entityManager->flush();

       
      
        return $this->redirectToRoute('app_detailSession', ['id'=> $session->getId()]);
      
          
    }  

}

templates/session/detailProgramme.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'une session{% endblock %}

{% block body %}
{% set category = "" %}
<div class="example-wrapper">

    <h1>Détail du programme d'une session {{session}}</h1>

    <p class="information">du {{session.dateDebut | date('m/d/Y')}} au {{session.dateFin | date('m/d/Y')}} {#affiche la date de debut et de fin de la session#}</p>
  
    <p class="information">Détail des modules:</p>
    <ul>
        {% for programme in session.programmes %}
            {% if programme.module.category != category %}
                 {% set category = programme.module.category %}
            
                <p><b>{{ programme.module.category }}:</b></p>
                {% endif %}
            <li class="detailModule">   
               <p>Module: <h3>{{ programme.module }} </h3></p>
               
                 
            </li>    
        {% endfor %}    
    </ul>
    
    <p class="detailModule">
        Liste des personnes inscrite <br>
        {% for stagiaire in session.stagiaires %}     
            <a href="{{ path('app_detailStagiaire', {'id': stagiaire.id})}}">{{stagiaire}} ;</a>    
        {% endfor %}
    </p>
    <a class="button" href="{{ path('edit_session',{'id': session.id}) }}">Modifier la session</a>
    <a class="button" href="{{ path('app_addStagiaire', {'id': session.id})}}">Ajouter un stagiaire</a>
    <a class="button" href="{{ path('app_addModuleSession', {'id': session.id})}}">Ajouter un module</a>
</div>
{% endblock %}

templates/session/detailSession.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail du programme d'une session{% endblock %}

{% block body %}
{% set category = "" %}
<div class="example-wrapper">

    <h1>Détail du programme de la session {{session}}</h1>

    <p class="information">du {{session.dateDebut | date('m/d/Y')}} au {{session.dateFin | date('m/d/Y')}} {#affiche la date de debut et de fin de la session#}</p>
  
    <p class="information">Détail des modules:</p>
    <ul>
        {% for programme in session.programmes %}
        {% if programme.module.category != category %}
                 {% set category = programme.module.category %}
            
                <p><b>{{ programme.module.category }}:</b></p>
                {% endif %}
            <li class="detailModule">   
               <p>Module: <h3>{{ programme.module }} </h3></p>
               <p>Durée: {{ programme.nbJours }} {{ (programme.nbJours) < 2 ? 'jour' : 'jours' }} </p>
               <a class="btn btn-warning" href="{{ path('app_unsetModule', {'id': programme.id})}}">Enlever</a>
               
                 
            </li>    
        {% endfor %}    
    </ul>
    
    <p class="detailModule">
        Liste des personnes inscrite <br>
        {% set count = 1 %}
        {% for stagiaire in session.stagiaires %}     
            <a href="{{ path('app_detailStagiaire', {'id': stagiaire.id})}}">{{ stagiaire }} <a class="btn btn-warning" href="{{ path('app_unsetStagiaire',{'id' : session.id ,'idStagiaire': stagiaire.id})}}">Enlever</a>  {{ (session.stagiaires)|length != count ? ' ,' : '.' }} </a>  
            {% set count = count + 1 %}            
        {% endfor %}
    </p>
    <a class="button" href="{{ path('edit_session',{'id': session.id}) }}">Modifier la session</a>
    <a class="button" href="{{ path('delete_session',{'id': session.id}) }}">Suprimer</a>
</div>
{% endblock %}

templates/session/detailStagiaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'une session{% endblock %}

{% block body %}

    <div class="example-wrapper">

        <h1>Fiche d'information satgiaire</h1>
        <a class="btn btn-warning" href="{{ path('edit_stagiaire',{'id':stagiaire.id}) }}">Edit</a>
        <h2>{{ stagiaire }}</h2>

        <p>Ville: {{ stagiaire.ville }}</p>
        <p>Email: {{ stagiaire.email }}</p>
        <p>Tel: {{ stagiaire.tel }}</p>
        <p>Date de Naissance: {{ stagiaire.dateNaissance | date('m/d/Y')}}</p>
        <p>Genre: {{ stagiaire.genre }}</p>
        <p>Age: {{ stagiaire.age }} ans.</p>
        <p>Liste des sessions inscrite:</p>
        {% for session in stagiaire.sessions %}
            <a href="{{ path('app_detailProgramme', {'id': session.id})}}"><p>{{ session }} du {{ session.dateDebut | date('m/d/Y')}} au {{ session.dateFin | date('m/d/Y')}}</p></a>
        {% endfor %} 
        </ul>
        
    </div>

{% endblock %}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'une session{% endblock %}

{% block body %}

<div class="container">
    <h1>Liste des Sessions </h1>
    
    <ul>
        {% for session in sessions %}
        <li>        
            <a href="{{ path('app_detailProgramme', {'id': session.id})}}">{{session}}</a>                      
        </li>        
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/session/listeCategories.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des categories{% endblock %}

{% block body %}

<div class="example-wrapper">
   <h1>Liste des categories</h1>

    <ul>
        {% for categorie in categories %}
            <li>
                {{categorie}}
            </li>
        {% endfor %}
  
    </ul>
</div>
{% endblock %}

templates/session/listeModules.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des modules{% endblock %}

{% block body %}

<div class="example-wrapper">
   <h1>Liste des Modules</h1>

    <ul>
        {% for module in modules %}
            <li>
                {{module}}
            </li>
        {% endfor %}
  
    </ul>
</div>
{% endblock %}

templates/session/listeSessionParFormation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'une session{% endblock %}

{% block body %}

<div class="container">

    <h1>Liste des sessions pour la formation {{formation}}</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-success table-striped">
                <tr>
                    <td>Intitule</td>
                    <td>Date de début</td>
                    <td>Date de fin</td>
                    <td>Etat</td>
                    <td>Nb de place totale</td>
                    <td>Nb de place restante</td>
                    <td>Détail du programme</td>
                </tr>
                {% for session in sessions %}
                    {% if session.etat != 'Terminé' %}
                        
                    
                        <tr>
                            <td>{{session}}</td>
                            <td>{{session.dateDebut | date('d/m/Y')}}</td>
                            <td>{{session.dateFin | date('d/m/Y')}}</td>
                            <td>{{session.etat}}</td>
                            <td>{{session.nbPlaceTotal}}</td>
                            <td>{{ session.nbPlaceTotal - session.stagiaires|length }}</td>
                            <td>
                                <a href="{{ path('app_detailSession', {'id': session.id})}}"><img class="detailProgramme" src="{{ asset('img/detail_programme.jpg')}}" alt="Détail du programmes"></a>
                                <a class="btn btn-warning" href="{{ path('edit_session',{'id': session.id }) }}">Edit</a>
                                
                            </td>
                        
                        </tr> 
                    {% endif %}    
                {% endfor %}
            </table>
        </div>
        <a class="button" href="{{ path('new_session',{'idFormation': formation.id}) }}">Ajouter une Session</a>
</div>
{% endblock %}

templates/session/new_formation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une Formation{% endblock %}

{% block body %}
<div class="container">
    {% if edit %}
    <h1>Modifier une formation {{formation}}</h1>
    {% else %}
    <h1>Ajouter une formation</h1> 
    {% endif %}
    

    {{ form_start(form) }}
        
        {{ form_row(form.intitule) }}
          
    {{ form_end(form) }}
</div>
{% endblock %}

templates/session/new_session.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter ou modifier une Session{% endblock %}

{% block body %}
<div class="container">
    {% if edit %}
        <h1>Modifier la Session: {{ session }}</h1>
    {% else %}
        <h1>Ajouter une Session a la formation {{ formation }}</h1>
    {% endif %}
    
    {{ form_start(form) }}
        
        {{ form_row(form.nbPlaceTotal) }}
        {{ form_row(form.dateDebut) }}
        {{ form_row(form.dateFin) }}
        {{ form_row(form.intitule) }}
        {# {{ form_row(form.formation) }} #}
        
        {# on va construire dynamiquement la liste des modules existants a partir de Programme #}
        <h2>Programme de la Session:</h2>
        <div class="form-group row ">
            <div class="col-form-label col-sm-2">&nbsp;</div>
            <div id="programme-fields-list" class="col-sm-10 remove-collection-widget"
                data-prototype="{{ form_widget(form.programmes.vars.prototype)|e }}"
                data-session="{{sessionId}}"
                data-widget-tags="{{ '<p></p>'|e }}"
                data-widget-counter="{{ form.programmes|length }}">
            {% for programmeField in form.programmes %}
                <p>
                    {{ form_errors(programmeField) }}
                    {{ form_widget(programmeField, {'attr': {'class': 'borders'}}) }}
                </p>
            {% endfor %}
            </div>
        </div>
        <div class="form-group row flex-action">
            <button type="button" 
                class="add-another-collection-widget button"
                data-list-selector="#programme-fields-list">Ajouter un nouveau module</button>
        </div>
    
     
    
        {# empêche l'apparition d'une légende "programmes", si la collection est vide (en cas de création d'une nouvelle session) #}
        {% do form.programmes.setRendered %}

</div>
{% endblock %}